name: Rebuild on upstream change

on:
  schedule:
    - cron: '17 6 * * *'   # run daily at 06:17
  workflow_dispatch:

env:
  UPSTREAM_REPO: caddy-dns/cloudflare   # <org>/<repo>

jobs:
  check-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read          # just checkout

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Restore last-seen upstream commit
      - name: Cache/restore last upstream SHA
        id: cache
        uses: actions/cache@v4
        with:
          path: .upstream-sha
          key: upstream-sha-${{ env.UPSTREAM_REPO }}
          # no restore-keys – we insist on exact match

      # Current upstream SHA
      - name: Get latest upstream SHA
        id: upstream
        run: |
          set -euo pipefail
          latest=$(curl -sSf \
                     -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                     "https://api.github.com/repos/${{ env.UPSTREAM_REPO }}/commits/master" \
                  | jq -r '.sha')

          [[ -z "$latest" || "$latest" = null ]] && {
            echo "::error::Could not fetch upstream SHA"
            exit 1
          }
          echo "sha=$latest" >> $GITHUB_OUTPUT

      # Compare
      - name: Check for change
        id: diff
        run: |
          last=""
          [[ -f .upstream-sha ]] && last=$(cat .upstream-sha)
          changed=$([ "$last" != "${{ steps.upstream.outputs.sha }}" ] && echo true || echo false)
          echo "changed=$changed" | tee -a $GITHUB_OUTPUT
          echo "last=$last / current=${{ steps.upstream.outputs.sha }}"

      # Early exit when nothing changed
      - name: Exit when no change
        if: steps.diff.outputs.changed != 'true'
        run: |
          echo "Upstream did not move – skipping build & update."
          exit 0

      # Build and push (only on change)
      - name: Set up Docker Buildx
        if: steps.diff.outputs.changed == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: steps.diff.outputs.changed == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push image
        if: steps.diff.outputs.changed == 'true'
        uses: docker/build-push-action@v6   # latest by default
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/caddy-cloudflare:latest

      # Persist the new SHA (runs *only* if build succeeded)
      - name: Save new upstream SHA
        if: steps.diff.outputs.changed == 'true'
        run: echo "${{ steps.upstream.outputs.sha }}" > .upstream-sha
