name: Rebuild image when upstream changes

on:
  schedule:
    - cron: '17 6 * * *'   # run daily at 06:17
  workflow_dispatch:       # manual trigger

env:
  UPSTREAM_REPO: caddy-dns/cloudflare   # owner/repo

jobs:
  check-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read            # needs only read; cache token uses repo scope

    steps:
      - name: Checkout my repo
        uses: actions/checkout@v4

      # --------- retrieve the SHA we saw last cycle --------
      - name: Retrieve last known upstream SHA
        uses: actions/cache@v4
        with:
          path: .upstream-sha
          key: upstream-sha-${{ env.UPSTREAM_REPO }}

      # --------- get the new SHA from the upstream repo ----
      - name: Determine latest upstream SHA
        id: upstream
        run: |
          set -euo pipefail
          latest=$(curl -sSf \
                     -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                     "https://api.github.com/repos/${{ env.UPSTREAM_REPO }}/commits/master" |
                   jq -r '.sha')

          if [[ -z "$latest" || "$latest" == "null" ]]; then
            echo "::error::Could not fetch upstream SHA"
            exit 1
          fi
          echo "sha=$latest" >> "$GITHUB_OUTPUT"

      # --------- compare SHAs and short-circuit if equal ----
      - name: Compare SHAs
        id: diff
        run: |
          last=""
          [[ -f .upstream-sha ]] && last=$(cat .upstream-sha)
          echo "Last known  : $last"
          echo "Current     : ${{ steps.upstream.outputs.sha }}"
          changed=$([ "$last" != "${{ steps.upstream.outputs.sha }}" ] && echo true || echo false)
          echo "changed=$changed" >> "$GITHUB_OUTPUT"

      - name: Exit early if nothing changed
        if: steps.diff.outputs.changed != 'true'
        run: |
          echo "No upstream change – skipping build."
          exit 0

      # --------- build & push the image --------------------
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/caddy-cloudflare:latest

      # --------- cache the new SHA for next run --------------
      - name: Save new upstream SHA in cache file
        run: echo "${{ steps.upstream.outputs.sha }}" > .upstream-sha
